version: "3.7"

services:
  mysql-service:
    image: mysql:latest
    networks:
      - spring-boot-mysql-network
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bank_rest
  soap-service:
    image: dockeryumi/bank.soap.service:latest
    networks:
      - spring-boot-mysql-network
  rest-service:
    image: dockeryumi/bank.rest.service:latest
    restart: always
    ports:
      - "4000:4000"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service
      - soap-service

networks:
  spring-boot-mysql-network:
    driver: bridge