package com.bankservice.bankdetails;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-02-17T20:54:15.423+05:30
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://bankservice.com/bankdetails", name = "AccountsPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AccountsPort {

    @WebMethod
    @WebResult(name = "transferToOwnAccountResponse", targetNamespace = "http://bankservice.com/bankdetails", partName = "transferToOwnAccountResponse")
    public TransferToOwnAccountResponse transferToOwnAccount(

        @WebParam(partName = "transferToOwnAccountRequest", name = "transferToOwnAccountRequest", targetNamespace = "http://bankservice.com/bankdetails")
        TransferToOwnAccountRequest transferToOwnAccountRequest
    );

    @WebMethod
    @WebResult(name = "getAccountBalancePerUserResponse", targetNamespace = "http://bankservice.com/bankdetails", partName = "getAccountBalancePerUserResponse")
    public GetAccountBalancePerUserResponse getAccountBalancePerUser(

        @WebParam(partName = "getAccountBalancePerUserRequest", name = "getAccountBalancePerUserRequest", targetNamespace = "http://bankservice.com/bankdetails")
        GetAccountBalancePerUserRequest getAccountBalancePerUserRequest
    );

    @WebMethod
    @WebResult(name = "getAccountBalanceResponse", targetNamespace = "http://bankservice.com/bankdetails", partName = "getAccountBalanceResponse")
    public GetAccountBalanceResponse getAccountBalance(

        @WebParam(partName = "getAccountBalanceRequest", name = "getAccountBalanceRequest", targetNamespace = "http://bankservice.com/bankdetails")
        GetAccountBalanceRequest getAccountBalanceRequest
    );

    @WebMethod
    @WebResult(name = "getAccountResponse", targetNamespace = "http://bankservice.com/bankdetails", partName = "getAccountResponse")
    public GetAccountResponse getAccount(

        @WebParam(partName = "getAccountRequest", name = "getAccountRequest", targetNamespace = "http://bankservice.com/bankdetails")
        GetAccountRequest getAccountRequest
    );

    @WebMethod
    @WebResult(name = "transferToOtherAccountResponse", targetNamespace = "http://bankservice.com/bankdetails", partName = "transferToOtherAccountResponse")
    public TransferToOtherAccountResponse transferToOtherAccount(

        @WebParam(partName = "transferToOtherAccountRequest", name = "transferToOtherAccountRequest", targetNamespace = "http://bankservice.com/bankdetails")
        TransferToOtherAccountRequest transferToOtherAccountRequest
    );
}
